// contains all the action type constants that is to be imported

 export const LOGIN = {
 	DATA_FETCH: 'DATA_FETCH',
 	DATA_FETCH_SUCCESS: 'DATA_FETCH_SUCCESS',
 	DATA_FETCH_FAILURE: 'DATA_FETCH_FAILURE',
 	TYPE_USERNAME: 'TYPE_USERNAME',
 	TYPE_PASSWORD: 'TYPE_PASSWORD',
 	FACEBOOK_LOGIN: 'FACEBOOK_LOGIN',
 	FACEBOOK_LOGIN_FAILURE: 'FACEBOOK_LOGIN_FAILURE',
 	FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS'
 }